### ISSUE TITLE
Not working on my machine

### ISSUE THREAD

**Issue by GJRobert** [mikethedj4/WebDGap#1]
Hi there, thanks a lot for your project and this looks promising.

As of now I cannot successfully build an app yet. I'm on a MacBook Air with OS X 10.11, using Firefox 47; I have also downloaded the Mac app for WebDGap. But what situation I'm facing is the same:
1. Entering "Wikiwand" as the app name.
2. Entering "http://wikiwand.com/" as the URL.
3. Apply.
4. Upon the dialog to choose a file to upload, I located an PNG file of Wikiwand logo and clicked on "Choose".
5. Nothing happens anymore.

Is there a clue about what I am missing? Thanks!

**Comment by mikethedj4** [comment]
Remember alternatively you can drag and drop an image in to load it instead. That works perfectly fine.

Thanks for the note on the other function though I wasn't aware of that bug. I'll work on it as soon as I can.

**Comment by mikethedj4** [comment]
The bug has been fixed! Thanks for telling me 👍

**Comment by GJRobert** [comment]
Thanks a lot! WebDGap is now working like a charm~

**Comment by mikethedj4** [comment]
No problem glad you like it!
