### ISSUE TITLE
[Q] Howto: make Mac .app from the downloaded folder?

### ISSUE THREAD

**Issue by GJRobert** [mikethedj4/WebDGap#2]
Hi Mike,

I have used WebDGap online to convert a site to a Mac app, and what I have got is the zip file with /data and run.sh inside.

I have edited the info.plist and changed the icon of the hello.app file inside /data, as explained in your informative [video](https://www.youtube.com/embed/-AszZcClVXA), so there is no problem executing the hello.app. (I have actually changed the filename of hello.app too as suggested, but for better recognizing I still call it hello.app here)

However, it seems that the hello.app cannot be moved directly to /Applications to run independently, and it depends on the whole /data directory. So this makes me wondering: if I want to make a single .app bundle file which works by itself, what should I do? Or is it ever possible?

Cheers
Robert

**Comment by mikethedj4** [comment]
So so if you have a Mac you can run Automator and add the code in run.sh into a shell script and create a mac app (hello.app) with automator. After that you can load in your project folder into it (inside "contents" if I recall correctly)  

Otherwise no you can't.

**Comment by GJRobert** [comment]
Successful! Here's all what I have done following your instructions, as an example and reference for future inquirers.

1. Convert, for example, http://wikiwand.com/ as an Mac app (name: `Wikiwand` for example) via WebDGap, and download the generated zip file. (I've got `wikiwand-macsite.zip` here)
1. Unzip the file, and change the filename, icon, bundle name etc. per instructed in [the video](https://www.youtube.com/embed/-AszZcClVXA).
1. Run Automator, choosing "Applications" as the project type.
1. Find "Run shell script" item and add it to the workflow.
1. Copy the code in the `run.sh` generated by WebDGap, and paste it into the "Run shell script" process.
1. Save the application in Automator. Here I'm using "Wikiwand". **The app name must be the same as what was given to WebDGap, otherwise the script will cause error.**
1. Open the saved Wikiwand.app with Finder "Open bundle"
1. Copy the `/data` folder into `/Contents` of the app bundle
1. That's it. The Wikiwand.app is now fully fledged.
1. Optionally change the icon of the app via Finder "Show Info" window or using 3rd party tools like **LiteIcon**★.
