### ISSUE TITLE
It might work... if it would download something...

### ISSUE THREAD

**Issue by sapioit** [mikethedj4/WebDGap#4]
# ^

**Comment by mikethedj4** [comment]
I don't understand what the problem is. Can you please elaborate?

**Comment by sapioit** [comment]
It opens the browser's download thing, and then it doesn't. Maybe you don't keep the file on the server enough time... or at all.

**Comment by mikethedj4** [comment]
WebDGap uses the HTML5 FileReader and FileSaver API's. Which means you need to use a browser that supports those API's. What browser are you using?

**Comment by sapioit** [comment]
Maxthon v4.4.8.2000, which is based off a chromium version from I think about a year ago... supports most of HTML5, and I didn't knew such thing existed... but why not try to maybe upload it on a free hosting somewhere?

**Comment by mikethedj4** [comment]
Does your console say?

Github Pages is free hosting and the desktop apps of WebDGap are hosted via SourceForge.

**Comment by mikethedj4** [comment]
I suggest using a support browser like Chrome/Firefox/Safari/ or Opera.
